export * from "./app.routs";
export * from "./nav-menu/nav-menu.component";
export * from "./aunt-form/aunt-form.component";
export * from "./registration-form/registration-form.component";
export * from "./notification/notification.component";
export * from "./clients-table/clients-table.component";
export * from "./popup/popup.component";
export * from "./client/client.component";
export * from "./home/home.component";